/** \file puertoSerie.hpp
    \brief Declaration of the ComSerial class that uses the SerialStream library.
    \author Edward Camilo
    \version 1.1 beta
    \date 2024
 */

#ifndef _PUERTO_SERIE_H_
    #define _PUERTO_SERIE_H_

    //extern "C"{
        #include <SerialStream.h>
    //}

    #include <sys/peripherals/capturer.hpp>

    class VoltageSignal;

    /** \brief Class that uses the serial port to the comunication with the external hardware.
        \class ComSerial
     */
    class ComSerial: public Capturer{
        /*Methods*/
        public:
            /** \brief Constructor that receive the voltage references that it will update.
             */
            ComSerial();

            /** \note Copy constructor desabled.
             */
            ComSerial(const ComSerial&) = delete;

            /** \note Operador assingment desabled.
             */
            ComSerial& operator=(const ComSerial&) = delete;

            /** \brief Destructor. Closes the port if it is open.
             */
            ~ComSerial();

            /** \brief Opens a serial port.
                \param port: File's path associated with the serial port generated by the kernel.
                \return Returns true, if the port is open and false if don't.
             */
            bool openPort(const char* port) override;

            /** \brief Closes a serial port.
                \return Returns true if it closes normaly or false id don't.
             */
            bool closePort() override;

            /** \brief Returns the port's state.
                \return False if is close, or true if is open.
             */
            bool getFlagSerial() override;

            TypeIdCapturer getId() override;

            /** \brief Reads 'n' values from the serial port to each one of the four voltages associates.
                Check the values arrive correctly from the external device.
                \param volt1: Reference to the voltage one.
                \param volt2: Reference to the voltage two.
                \param volt3: Reference to the voltage three.
                \param volt4: Reference to the voltage four.
                \param nValues : Amount of values to read by voltage signal.
                \override
             */
            void readValues(VoltageSignal *volt1, VoltageSignal *volt2,
                            VoltageSignal *volt3, VoltageSignal *volt4,
                            unsigned int nValues) override;

            /** \brief Sends the sample rate to the required frequency.
                \param freq : Requied frequency.
                \override
             */
            void setSampleFrequency(unsigned int freq) override;
        private:
            /** \brief Checks if the line captured into the stream, start by certain characters.
                \param line: String that obtains the line of the capture data by the stream.
                \param text: Starting characters.
             */
            bool startWith(std::string line, const char* text);

        /*Attributes*/
        private:
            LibSerial::SerialStream mySerial;  ///< SerialStream associte with a port
    };

#endif
