/** \file puertoSerie.hpp
    \brief Declaration of the ComSerial class that uses the SerialStream library.
    \author Edward Camilo
    \version 1.1 beta
    \date 2024
 */

#ifndef _PUERTO_SERIE_H_
    #define _PUERTO_SERIE_H_

    //extern "C"{
        #include <SerialStream.h>
    //}

    #include <sys/peripherals/capturer.hpp>

    class VoltageSignal;

    /** \brief Class that uses the serial port to the comunication with the external hardware.
        \class ComSerial
     */
    class ComSerial: public Capturer{
        /*Methods*/
        public:
            /** \brief Constructor that receive the voltage references that it will update.
                \param volt1 Pointer associate with the voltage1.
                \param volt2 Pointer associate with the voltage2.
                \param volt3 Pointer associate with the voltage3.
                \param volt4 Pointer associate with the voltage4.
             */
            ComSerial(VoltageSignal *volt1, VoltageSignal *volt2, VoltageSignal *volt3, VoltageSignal *volt4);

            /** \note Copy constructor desabled.
             */
            ComSerial(const ComSerial&) = delete;

            /** \note Operador assingment desabled.
             */
            ComSerial& operator=(const ComSerial&) = delete;

            /** \brief Destructor. Closes the port if it is open.
             */
            ~ComSerial();

            /** \brief Opens a serial port.
                \param port: File's path associated with the serial port generated by the kernel.
                \return Returns true, if the port is open and false if don't.
             */
            bool openPort(const char* port);

            /** \brief Closes a serial port.
                \return Returns true if it closes normaly or false id don't.
             */
            bool closePort();

            /** \brief Returns the port's state.
                \return False if is close, or true if is open.
             */
            bool getFlagSerial();

            /** \brief Reads 'n' values from the serial port to each one of the four voltages associates.
                Check the values arrive correctly from the external device.
                \param nValues : Amount of values to read by voltage signal.
                \override
             */
            void readValues(unsigned int nValues) override;

            /** \brief Sends the sample rate to the required frequency.
                \param freq : Requied frequency.
                \override
             */
            void setSampleFrequency(unsigned int freq) override;
        private:
            /** \brief Shifts the signals associates with the voltages for its subsequent capture.
                \param n: Amount of values to shift.
             */
            void scrollVoltages(unsigned int n);

            /** \brief Checks if the line captured into the stream, start by certain characters.
                \param line: String that obtains the line of the capture data by the stream.
                \param text: Starting characters.
             */
            bool startWith(std::string line, const char* text);

        /*Attributes*/
        private:
            LibSerial::SerialStream mySerial;  ///< SerialStream associte with a port
            VoltageSignal *voltage1 {nullptr}; /**< Voltage1 */
            VoltageSignal *voltage2 {nullptr}; /**< Voltage2 */
            VoltageSignal *voltage3 {nullptr}; /**< Voltage3 */
            VoltageSignal *voltage4 {nullptr}; /**< Voltage4 */
            float *valuesCatched1 {nullptr}; /**< Array associate with voltage1 signal*/
            float *valuesCatched2 {nullptr}; /**< Array associate with voltage2 signal */
            float *valuesCatched3 {nullptr}; /**< Array associate with voltage3 signal */
            float *valuesCatched4 {nullptr}; /**< Array associate with voltage4 signal */
    };

#endif
