/** \file puertoSerie.hpp
 *  \brief Declaration of the ComSerial class that uses the SerialStream library.
 *  \author Edward Camilo
 *  \version 1.1 beta
 *  \date May 2026
 */
#pragma once

#include <SerialStream.h>
#include "application/ICapturer.hpp"

namespace APP{
    struct IScreen;
}

namespace DRV_FRAMW{
    /** \brief Class that uses the serial port to the comunication with the external hardware.
        \class ComSerial
     */
    class SerialPortAnyMcu: public APP::ICapturer{
        //====================
        // METHODS
        //====================
        public:
            /** \brief Constructor that receive the voltage references that it will update.
             */
            [[nodiscard]] SerialPortAnyMcu();

            /** \note Copy-Constructor disabled.
             */
            SerialPortAnyMcu(const SerialPortAnyMcu &other) = delete;

            /** \note Move-Constructor disabled.
             *  \param other: SerialPortAnyMcu object.
             */
            SerialPortAnyMcu(SerialPortAnyMcu &&other) = delete;

            /** \brief Destructor. Closes the port if it is open.
             */
            ~SerialPortAnyMcu();

            /** \note Assignment operator disabled.
             */
            SerialPortAnyMcu& operator =(const SerialPortAnyMcu&) = delete;
            SerialPortAnyMcu& operator =(SerialPortAnyMcu &&other) = delete;

            /**
             * 
             */
            void associate_screen(APP::IScreen* screenPtr) override final;

            /** \brief Opens a serial port.
                \param port: File's path associated with the serial port generated by the kernel.
                \return Returns true, if the port is open and false if don't.
             */
            int open_port(const char* port) override final;

            /** \brief Closes a serial port.
                \return Returns true if it closes normaly or false id don't.
             */
            int close_port() override final;

            /** \brief Reads 'n' values from the serial port to each one of the four voltages associates.
                Check the values arrive correctly from the external device.
                \param userData:
                \override
             */
            void catch_data(void *userData) override final;

            /** \brief Sends the sample rate to the required frequency.
                \param userData : .
                \override
             */
            void set_data(void* userData) override final;

            /** \brief Returns the port's state.
                \return False if is close, or true if is open.
             */
            bool get_flag_serial() override final;

            APP::IdCapturer_t get_Id() override final;

        private:
            /** \brief Checks if the line captured into the stream, start by certain characters.
                \param line: String that obtains the line of the capture data by the stream.
                \param text: Starting characters.
             */
            bool start_with(std::string line, const char* text);

        //====================
        // ATTRIBUTES
        //====================
        private:
            APP::IScreen*           screenPtr_ {nullptr};
            LibSerial::SerialStream mySerial_;  ///< SerialStream associte with a port
    };
}
