/** \file puertoSerie.hpp
    \brief Declaration of the ComSerial class that uses the SerialStream library.
    \author Edward Camilo
    \version 1.1 beta
    \date 2024
 */

#ifndef ED_PUERTO_SERIE_H_
    #define ED_PUERTO_SERIE_H_

    //extern "C"{
        #include <SerialStream.h>
    //}

    #include <utils/capturers/capturer.hpp>

    //==================================================
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // FORWARD DECLARATION
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //==================================================
    class VoltageSignal;

    //==================================================
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    // CLASS
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    //==================================================
    /** \brief Class that uses the serial port to the comunication with the external hardware.
        \class ComSerial
     */
    class SerialPort: public Capturer{
        //==========
        //~~~~~~~~~~
        // METHODS
        //~~~~~~~~~~
        //==========
        public:
            /** \brief Constructor that receive the voltage references that it will update.
             */
            SerialPort();

            /** \note Copy constructor desabled.
             */
            SerialPort(const SerialPort&) = delete;

            /** \note Operador assingment desabled.
             */
            SerialPort& operator=(const SerialPort&) = delete;

            /** \brief Destructor. Closes the port if it is open.
             */
            ~SerialPort();

            /** \brief Opens a serial port.
                \param port: File's path associated with the serial port generated by the kernel.
                \return Returns true, if the port is open and false if don't.
             */
            int open_port(const char* port) override;

            /** \brief Closes a serial port.
                \return Returns true if it closes normaly or false id don't.
             */
            int close_port() override;

            /** \brief Returns the port's state.
                \return False if is close, or true if is open.
             */
            bool get_flag_serial() override;

            IdCapturer_t get_Id() override;

            /** \brief Reads 'n' values from the serial port to each one of the four voltages associates.
                Check the values arrive correctly from the external device.
                \param volt1: Reference to the voltage one.
                \param volt2: Reference to the voltage two.
                \param volt3: Reference to the voltage three.
                \param volt4: Reference to the voltage four.
                \param nValues : Amount of values to read by voltage signal.
                \override
             */
            void read_values(
                VoltageSignal *volt1,
                VoltageSignal *volt2,
                VoltageSignal *volt3,
                VoltageSignal *volt4,
                unsigned int nValues
            ) override;

            /** \brief Sends the sample rate to the required frequency.
                \param freq : Requied frequency.
                \override
             */
            void set_sample_frequency(unsigned int freq) override;
        private:
            /** \brief Checks if the line captured into the stream, start by certain characters.
                \param line: String that obtains the line of the capture data by the stream.
                \param text: Starting characters.
             */
            bool start_with(std::string line, const char* text);

        //==========
        //~~~~~~~~~~
        // ATTRIBUTES
        //==========
        //~~~~~~~~~~
        private:
            LibSerial::SerialStream mySerial_;  ///< SerialStream associte with a port
    };

#endif
